//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerStoreApp.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public Customers()
        {
            this.Sales = new HashSet<Sales>();
        }
    
        public int CustomerId { get; set; }
        public string LoyaltyCardNumber { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public System.DateTime RegistrationDate { get; set; }
    
        public virtual ICollection<Sales> Sales { get; set; }
    }
}
