//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerStoreApp.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deliveries
    {
        public Deliveries()
        {
            this.DeliveryItems = new HashSet<DeliveryItems>();
        }
    
        public int DeliveryId { get; set; }
        public int SupplierId { get; set; }
        public int StoreId { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string InvoiceNumber { get; set; }
    
        public virtual Stores Stores { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual ICollection<DeliveryItems> DeliveryItems { get; set; }
    }
}
