//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerStoreApp.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.DeliveryItems = new HashSet<DeliveryItems>();
            this.SaleItems = new HashSet<SaleItems>();
            this.StockBalances = new HashSet<StockBalances>();
        }
    
        public int ProductId { get; set; }
        public string SKU { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<int> WarrantyMonths { get; set; }
        public string Specs { get; set; }
    
        public virtual ICollection<DeliveryItems> DeliveryItems { get; set; }
        public virtual ICollection<SaleItems> SaleItems { get; set; }
        public virtual ICollection<StockBalances> StockBalances { get; set; }
    }
}
