//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerStoreApp.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public Sales()
        {
            this.SaleItems = new HashSet<SaleItems>();
        }
    
        public int SaleId { get; set; }
        public int StoreId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public System.DateTime SaleDate { get; set; }
        public decimal TotalAmount { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual ICollection<SaleItems> SaleItems { get; set; }
        public virtual Stores Stores { get; set; }
    }
}
