//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerStoreApp.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stores
    {
        public Stores()
        {
            this.Deliveries = new HashSet<Deliveries>();
            this.Employees = new HashSet<Employees>();
            this.Sales = new HashSet<Sales>();
            this.StockBalances = new HashSet<StockBalances>();
        }
    
        public int StoreId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Deliveries> Deliveries { get; set; }
        public virtual ICollection<Employees> Employees { get; set; }
        public virtual ICollection<Sales> Sales { get; set; }
        public virtual ICollection<StockBalances> StockBalances { get; set; }
    }
}
