//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerStoreApp.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppliers
    {
        public Suppliers()
        {
            this.Deliveries = new HashSet<Deliveries>();
        }
    
        public int SupplierId { get; set; }
        public string Name { get; set; }
        public string ContactPerson { get; set; }
        public string Phone { get; set; }
        public string TaxId { get; set; }
    
        public virtual ICollection<Deliveries> Deliveries { get; set; }
    }
}
